definitions:
  models.BinlogValidation:
    properties:
      error:
        description: Error is a string version of any error that may have occured
        type: string
      validated:
        type: boolean
    type: object
  models.ConnectionValidation:
    properties:
      error:
        description: Error is a string version of any error that may have occured
        type: string
      validated:
        type: boolean
    type: object
  models.CreateOrUpdateMysqlToMysqlJobParamV2:
    properties:
      dest_task:
        $ref: '#/definitions/models.MysqlDestTaskConfig'
      failover:
        description: TODO:to find out the usage of it
        type: boolean
      job_id:
        type: string
      job_name:
        type: string
      src_task:
        $ref: '#/definitions/models.MysqlSrcTaskConfig'
    required:
    - job_name
    type: object
  models.CreateOrUpdateMysqlToMysqlJobRespV2:
    properties:
      dest_task:
        $ref: '#/definitions/models.MysqlDestTaskConfig'
      eval_create_index:
        type: integer
      failover:
        description: TODO:to find out the usage of it
        type: boolean
      job_id:
        type: string
      job_modify_index:
        type: integer
      job_name:
        type: string
      message:
        type: string
      src_task:
        $ref: '#/definitions/models.MysqlSrcTaskConfig'
    required:
    - job_name
    type: object
  models.GtidModeValidation:
    properties:
      error:
        description: Error is a string version of any error that may have occured
        type: string
      validated:
        type: boolean
    type: object
  models.JobDetailRespV2:
    properties:
      dest_task_detail:
        $ref: '#/definitions/models.MysqlDestTaskDetail'
      failover:
        description: TODO:to find out the usage of it
        type: boolean
      job_id:
        type: string
      job_name:
        type: string
      message:
        type: string
      src_task_detail:
        $ref: '#/definitions/models.MysqlSrcTaskDetail'
    type: object
  models.JobListItemV2:
    properties:
      job_id:
        type: string
      job_name:
        type: string
      job_status:
        type: string
      job_status_description:
        type: string
    type: object
  models.JobListRespV2:
    properties:
      jobs:
        items:
          $ref: '#/definitions/models.JobListItemV2'
        type: array
      message:
        type: string
    type: object
  models.MysqlConnectionConfig:
    properties:
      mysql_host:
        type: string
      mysql_password:
        description: 'TODO: encrypt'
        type: string
      mysql_port:
        type: integer
      mysql_user:
        type: string
    required:
    - mysql_host
    - mysql_password
    - mysql_port
    - mysql_user
    type: object
  models.MysqlDataSourceConfig:
    properties:
      table_schema:
        type: string
      table_schema_rename:
        type: string
      tables:
        items:
          $ref: '#/definitions/models.MysqlTableConfig'
        type: array
    required:
    - table_schema
    type: object
  models.MysqlDestTaskConfig:
    properties:
      mysql_connection_config:
        $ref: '#/definitions/models.MysqlConnectionConfig'
      node_id:
        type: string
      parallel_workers:
        type: integer
      task_name:
        type: string
    required:
    - mysql_connection_config
    - task_name
    type: object
  models.MysqlDestTaskDetail:
    properties:
      task_config:
        $ref: '#/definitions/models.MysqlDestTaskConfig'
      task_status:
        $ref: '#/definitions/models.TaskStatus'
    type: object
  models.MysqlSrcTaskConfig:
    properties:
      chunk_size:
        type: integer
      drop_table_if_exists:
        type: boolean
      group_max_size:
        type: integer
      gtid:
        type: string
      mysql_connection_config:
        $ref: '#/definitions/models.MysqlConnectionConfig'
      node_id:
        type: string
      repl_chan_buffer_size:
        type: integer
      replicate_do_db:
        items:
          $ref: '#/definitions/models.MysqlDataSourceConfig'
        type: array
      replicate_ignore_db:
        items:
          $ref: '#/definitions/models.MysqlDataSourceConfig'
        type: array
      skip_create_db_table:
        type: boolean
      task_name:
        type: string
    required:
    - mysql_connection_config
    - task_name
    type: object
  models.MysqlSrcTaskDetail:
    properties:
      task_config:
        $ref: '#/definitions/models.MysqlSrcTaskConfig'
      task_status:
        $ref: '#/definitions/models.TaskStatus'
    type: object
  models.MysqlTableConfig:
    properties:
      column_map_from:
        items:
          type: string
        type: array
      table_name:
        type: string
      table_rename:
        type: string
      where:
        type: string
    required:
    - table_name
    type: object
  models.MysqlTaskValidationReport:
    properties:
      binlog_validation:
        $ref: '#/definitions/models.BinlogValidation'
      connection_validation:
        $ref: '#/definitions/models.ConnectionValidation'
      gtid_mode_validation:
        $ref: '#/definitions/models.GtidModeValidation'
      privileges_validation:
        $ref: '#/definitions/models.PrivilegesValidation'
      server_id_validation:
        $ref: '#/definitions/models.ServerIDValidation'
      task_name:
        type: string
    type: object
  models.NodeListItemV2:
    properties:
      datacenter:
        type: string
      node_address:
        type: string
      node_id:
        type: string
      node_name:
        type: string
      node_status:
        type: string
      node_status_description:
        type: string
    type: object
  models.NodeListRespV2:
    properties:
      message:
        type: string
      nodes:
        items:
          $ref: '#/definitions/models.NodeListItemV2'
        type: array
    type: object
  models.PrivilegesValidation:
    properties:
      error:
        description: Error is a string version of any error that may have occured
        type: string
      validated:
        type: boolean
    type: object
  models.ServerIDValidation:
    properties:
      error:
        description: Error is a string version of any error that may have occured
        type: string
      validated:
        type: boolean
    type: object
  models.TaskEvent:
    properties:
      event_type:
        type: string
      message:
        type: string
      setup_error:
        type: string
      time:
        type: string
    type: object
  models.TaskStatus:
    properties:
      finished_at:
        type: string
      started_at:
        type: string
      status:
        type: string
      task_events:
        items:
          $ref: '#/definitions/models.TaskEvent'
        type: array
    type: object
  models.ValidateJobReqV2:
    properties:
      dest_task:
        $ref: '#/definitions/models.MysqlDestTaskConfig'
      job_id:
        type: string
      job_name:
        type: string
      src_task:
        $ref: '#/definitions/models.MysqlSrcTaskConfig'
    required:
    - dest_task
    - job_name
    - src_task
    type: object
  models.ValidateJobRespV2:
    properties:
      driver_config_validated:
        description: DriverConfigValidated indicates whether the agent validated the
          driver
        type: boolean
      job_validation_error:
        type: string
      job_validation_warning:
        type: string
      message:
        type: string
      mysql_task_validation_report:
        description: config
        items:
          $ref: '#/definitions/models.MysqlTaskValidationReport'
        type: array
    type: object
  v2.UpdataLogLevelRespV2:
    properties:
      dtle_log_level:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /v2/job/detail:
    get:
      description: get job detail.
      parameters:
      - description: job id
        in: query
        name: job_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JobDetailRespV2'
      tags:
      - job
  /v2/job/migration:
    post:
      consumes:
      - application/json
      description: create or update migration job.
      parameters:
      - description: migration job config
        in: body
        name: migration_job_config
        required: true
        schema:
          $ref: '#/definitions/models.CreateOrUpdateMysqlToMysqlJobParamV2'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CreateOrUpdateMysqlToMysqlJobRespV2'
      tags:
      - job
  /v2/jobs:
    get:
      description: get job list.
      parameters:
      - description: filter job type
        in: query
        name: filter_job_type
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JobListRespV2'
      tags:
      - job
  /v2/log_level:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: reload log level dynamically.
      parameters:
      - description: dtle log level
        enum:
        - TRACE
        - DEBUG
        - INFO
        - WARN
        - ERROR
        in: formData
        name: dtle_log_level
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v2.UpdataLogLevelRespV2'
      tags:
      - log
  /v2/nodes:
    get:
      description: get node list.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.NodeListRespV2'
      tags:
      - node
  /v2/validation/job:
    post:
      consumes:
      - application/json
      description: validate job config.
      parameters:
      - description: validate job config
        in: body
        name: job_config
        required: true
        schema:
          $ref: '#/definitions/models.ValidateJobReqV2'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ValidateJobRespV2'
      tags:
      - validation
swagger: "2.0"
